//@version=5
strategy("Supertrend Tuple [Alorse]", overlay=true, pyramiding=0, currency=currency.USD, default_qty_type=strategy.percent_of_equity, initial_capital=1000, default_qty_value=10, commission_type=strategy.commission.percent, commission_value=0.01)

factor = input.float(3.0, step=0.1, title="Factor")

[st, dir] = ta.supertrend(factor, 10)

longEntry  = dir == 1 and dir[1] == -1
shortEntry = dir == -1 and dir[1] == 1

strategy.entry("Long",  strategy.long,  when=longEntry)
strategy.close("Long",  when=shortEntry)
strategy.entry("Short", strategy.short, when=shortEntry)
strategy.close("Short", when=longEntry)

plot(dir == 1 ? st : na, title="Up",   color=color.green, linewidth=2)
plot(dir == -1 ? st : na, title="Down", color=color.red,   linewidth=2)
