package golden

// sizeResidualCase describes a single (strategy, data, golden) triple for the
// exhaustive sizing-residual sweep. strategyRelPath is relative to the
// workspace root and resolves both "strategies/" and "e2e/fixtures/strategies/"
// entries without any routing logic in the sweep test.
type sizeResidualCase struct {
	strategyRelPath string
	dataFile        string
	goldenFile      string
	symbol          string
	timeframe       string
}

// allStrategyGoldens lists every golden case whose strategy result contains at
// least one closed trade. TestSizeResidual_AllGoldens sweeps this list.
// TestRegistry_CoversAllStrategyGoldens validates completeness at every run.
var allStrategyGoldens = []sizeResidualCase{
	{strategyRelPath: "strategies/adx-di-strategy.pine", dataFile: "AAPL-1h.json", goldenFile: "adx-di-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/adx-di-strategy.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "adx-di-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/adx-di-strategy.pine", dataFile: "CNRU-1h.json", goldenFile: "adx-di-cnru-1h.json", symbol: "CNRU", timeframe: "1h"},
	{strategyRelPath: "strategies/adx-di-strategy.pine", dataFile: "SBERP-1h.json", goldenFile: "adx-di-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/ann-sirolf.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "ann_sirolf_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-rsi-strategy.pine", dataFile: "AAPL-1h.json", goldenFile: "bb-rsi-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-rsi-strategy.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "bb-rsi-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-rsi-strategy.pine", dataFile: "SBERP-1h.json", goldenFile: "bb-rsi-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-7-rus.pine", dataFile: "AAPL-1h.json", goldenFile: "bb7-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-7-rus.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "bb7-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-7-rus.pine", dataFile: "SBERP-1h.json", goldenFile: "bb7-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-8-rus.pine", dataFile: "AAPL-1h.json", goldenFile: "bb8-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-8-rus.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "bb8-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-8-rus.pine", dataFile: "SBERP-1h.json", goldenFile: "bb8-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/bb-strategy-9-rus.pine", dataFile: "SBERP-1h.json", goldenFile: "bb9-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/heikin-ashi-test.pine", dataFile: "AAPL_1D.json", goldenFile: "heikin-ashi-aapl-1d.json", symbol: "AAPL", timeframe: "1D"},
	{strategyRelPath: "strategies/heikin-ashi-test.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "heikin-ashi-btcusdt-1d.json", symbol: "BTCUSDT", timeframe: "1D"},
	{strategyRelPath: "strategies/kc-tuple.pine", dataFile: "AAPL-1h.json", goldenFile: "kc-tuple-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/kc-tuple.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "kc-tuple-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/kc-tuple.pine", dataFile: "SBERP-1h.json", goldenFile: "kc-tuple-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/keltner-squeeze.pine", dataFile: "AAPL-1h.json", goldenFile: "keltner-squeeze-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/keltner-squeeze.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "keltner-squeeze-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/keltner-squeeze.pine", dataFile: "PLZL-1h.json", goldenFile: "keltner-squeeze-plzl-1h.json", symbol: "PLZL", timeframe: "1h"},
	{strategyRelPath: "strategies/keltner-squeeze.pine", dataFile: "SBERP-1h.json", goldenFile: "keltner-squeeze-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/macd-crossover.pine", dataFile: "AAPL-1h.json", goldenFile: "macd-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/macd-crossover.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "macd-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/macd-crossover.pine", dataFile: "SBERP-1h.json", goldenFile: "macd-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/mtf-confirmation-strategy.pine", dataFile: "AAPL-1h.json", goldenFile: "mtf-confirmation-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/mtf-confirmation-strategy.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "mtf-confirmation-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/mtf-confirmation-strategy.pine", dataFile: "NVDA-1h.json", goldenFile: "mtf-confirmation-nvda-1h.json", symbol: "NVDA", timeframe: "1h"},
	{strategyRelPath: "strategies/mtf-confirmation-strategy.pine", dataFile: "SBERP-1h.json", goldenFile: "mtf-confirmation-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/rsi-strategy.pine", dataFile: "AAPL-1h.json", goldenFile: "rsi-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/rsi-strategy.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "rsi-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/rsi-strategy.pine", dataFile: "NVDA-1h.json", goldenFile: "rsi-nvda-1h.json", symbol: "NVDA", timeframe: "1h"},
	{strategyRelPath: "strategies/rsi-strategy.pine", dataFile: "SBERP-1h.json", goldenFile: "rsi-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend-tuple.pine", dataFile: "AAPL-1h.json", goldenFile: "supertrend-tuple-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend-tuple.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "supertrend-tuple-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend-tuple.pine", dataFile: "SBERP-1h.json", goldenFile: "supertrend-tuple-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend.pine", dataFile: "AAPL-1h.json", goldenFile: "supertrend-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "supertrend-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/supertrend.pine", dataFile: "SBERP-1h.json", goldenFile: "supertrend-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-computed-period-diverse.pine", dataFile: "AAPL-1h.json", goldenFile: "arrow_computed_period_diverse_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-computed-period-diverse.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "arrow_computed_period_diverse_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-computed-period.pine", dataFile: "AAPL-1h.json", goldenFile: "arrow_computed_period_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-computed-period.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "arrow_computed_period_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-delegated-math.pine", dataFile: "AAPL-1h.json", goldenFile: "arrow_delegated_math_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-arrow-delegated-math.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "arrow_delegated_math_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/test-arrow-implicit-ohlc.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "arrow-implicit-ohlc-btcusdt-1d.json", symbol: "BTCUSDT", timeframe: "1D"},
	{strategyRelPath: "strategies/test-arrow-multiarg-overload.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "arrow-multiarg-overload-btcusdt-1d.json", symbol: "BTCUSDT", timeframe: "1D"},
	{strategyRelPath: "e2e/fixtures/strategies/test-color-functions.pine", dataFile: "AAPL-1h.json", goldenFile: "color_functions_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-color-functions.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "color_functions_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-conditional-coercion-forloop.pine", dataFile: "AAPL-1h.json", goldenFile: "conditional_coercion_forloop_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-conditional-coercion-forloop.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "conditional_coercion_forloop_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-conditional-coercion-mixed.pine", dataFile: "AAPL-1h.json", goldenFile: "conditional_coercion_mixed_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-conditional-coercion-mixed.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "conditional_coercion_mixed_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-dmi-crossover.pine", dataFile: "AAPL-1h.json", goldenFile: "dmi-crossover-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-dmi-crossover.pine", dataFile: "CNRU-1h.json", goldenFile: "dmi-crossover-cnru-1h.json", symbol: "CNRU", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-dmi-strategy.pine", dataFile: "AAPL-1h.json", goldenFile: "dmi-strategy-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-dmi-strategy.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "dmi-strategy-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-conditional-accumulation.pine", dataFile: "AAPL-1h.json", goldenFile: "for_loop_conditional_accumulation_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-conditional-accumulation.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "for_loop_conditional_accumulation_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-momentum-cascade.pine", dataFile: "AAPL-1h.json", goldenFile: "momentum_cascade_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-momentum-cascade.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "momentum_cascade_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-momentum-cascade.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "momentum_cascade_btcusdt_1d.golden.json", symbol: "BTCUSDT", timeframe: "D"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-momentum-cascade.pine", dataFile: "RBLX_1h.json", goldenFile: "momentum_cascade_rblx_1h.golden.json", symbol: "RBLX", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-simple-counter.pine", dataFile: "AAPL-1h.json", goldenFile: "for_loop_simple_counter_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-for-loop-simple-counter.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "for_loop_simple_counter_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/test-math-functions.pine", dataFile: "AAPL-1h.json", goldenFile: "math-functions-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/test-math-functions.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "math-functions-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/test-math-functions.pine", dataFile: "SBERP-1h.json", goldenFile: "math-functions-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-math-unprefixed.pine", dataFile: "AAPL-1h.json", goldenFile: "math-unprefixed-aapl-1h.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-math-unprefixed.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "math-unprefixed-btcusdt-1h.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-math-unprefixed.pine", dataFile: "SBERP-1h.json", goldenFile: "math-unprefixed-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-ticker-standard.pine", dataFile: "AAPL_1D.json", goldenFile: "ticker_standard_aapl_1d.golden.json", symbol: "AAPL", timeframe: "1D"},
	{strategyRelPath: "e2e/fixtures/strategies/test-ticker-standard.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "ticker_standard_btcusdt_1d.golden.json", symbol: "BTCUSDT", timeframe: "1D"},
	{strategyRelPath: "e2e/fixtures/strategies/test-value-functions-arrow-args.pine", dataFile: "AAPL-1h.json", goldenFile: "value_functions_arrow_args_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-value-functions-arrow-args.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "value_functions_arrow_args_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-break.pine", dataFile: "AAPL-1h.json", goldenFile: "while_break_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-break.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "while_break_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-continue.pine", dataFile: "AAPL-1h.json", goldenFile: "while_continue_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-continue.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "while_continue_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-loop-factorial.pine", dataFile: "AAPL-1h.json", goldenFile: "while_loop_factorial_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-loop-factorial.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "while_loop_factorial_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-loop-sum.pine", dataFile: "AAPL-1h.json", goldenFile: "while_loop_sum_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "e2e/fixtures/strategies/test-while-loop-sum.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "while_loop_sum_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/alpha.pine", dataFile: "AAPL-1h.json", goldenFile: "alpha_trend_aapl_1h.golden.json", symbol: "AAPL", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/alpha.pine", dataFile: "BTCUSDT-1h.json", goldenFile: "alpha_trend_btcusdt_1h.golden.json", symbol: "BTCUSDT", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/alpha.pine", dataFile: "SBERP-1h.json", goldenFile: "alpha_trend_sberp_1h.golden.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/aostoch.pine", dataFile: "SBERP-1h.json", goldenFile: "aostoch-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/hull.pine", dataFile: "SBERP-1h.json", goldenFile: "hull-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/max.pine", dataFile: "SBERP-1h.json", goldenFile: "max-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/zigzag.pine", dataFile: "SBERP-1h.json", goldenFile: "zigzag-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/top10/moon.pine", dataFile: "AAPL-M.json", goldenFile: "moon_phases_aapl_m.golden.json", symbol: "AAPL", timeframe: "1M"},
	{strategyRelPath: "strategies/top10/moon.pine", dataFile: "BTCUSDT-M.json", goldenFile: "moon_phases_btcusdt_m.golden.json", symbol: "BTCUSDT", timeframe: "1M"},
	{strategyRelPath: "strategies/top10/moon.pine", dataFile: "SBERP-M.json", goldenFile: "moon_phases_sberp_m.golden.json", symbol: "SBERP", timeframe: "1M"},
	{strategyRelPath: "strategies/top10/ut+.pine", dataFile: "SBERP-1h.json", goldenFile: "ut-plus-sberp-1h.json", symbol: "SBERP", timeframe: "1h"},
	{strategyRelPath: "strategies/utbot-quantnomad.pine", dataFile: "AAPL_1D.json", goldenFile: "utbot-aapl-1d.json", symbol: "AAPL", timeframe: "1D"},
	{strategyRelPath: "strategies/utbot-quantnomad.pine", dataFile: "BTCUSDT_1D.json", goldenFile: "utbot-btcusdt-1d.json", symbol: "BTCUSDT", timeframe: "1D"},
}
